spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_vendor?useSSL=false
    username: root
    password: D!lemma628


    #to be added in case swagger fails to load
    mvc:
      pathmatch:
        matching-strategy: ANT_PATH_MATCHER

#HIBERNATE HANDLES DATABASE QUERIES UPON APPLICATION BUILD
  jpa:
    hibernate:
      ddl-auto: update

#to include all available actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: "health, beans, metrics" #only those 3 endpoints will be available
        #below is the code:
        #to exclude an endpoint -> exclude: "caches"
        #to include all endpoints -> include: "*"
      base-path: "/management-dashboard" #replaces default path /actuator with /management-dashboard
  #this is to show more details from the health endpoint itself
  endpoint:
    health:
      show-details: always